---
title: ''
author: ''
date: ''
output: 
  html_document:
    df_print: paged
    keep_md: true
  word_document:
    reference_docx: style.1.docx
---

```{r setup, include = FALSE}

  knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                        fig.width  = 6 * 1.67, fig.height = 6)


# load("data/data.RData")
  source("scripts/01_data.R")
  source("scripts/functions.R")

  library(tidyverse)
  library(descr)
  library(viridis)
  library(RColorBrewer)
  library(flextable)
  library(knitr)
  library(pander)
  library(sjPlot)
  library(patchwork)
  library(survival)
  library(survminer)

  
```

# Overview

## Initial goals

# Main Sample

The overall dataset includes `r nrow(data)` patients. 

```{r time_lines}

  levs <- c("date_of_dx", "x1st_treatment", "relapse_1_progression",
            "relapse_2_progression", "relapse_3_progression", 
            "date_rip_last_f_up")

  labs <- c("Diagnosis", "First Tx", "First Relapse", "Second Relapse", 
            "Third Relapse", "End of Observation")

  times <- data %>%
    select(id, outcome, 
           date_of_dx, x1st_treatment, 
           relapse_1_progression, relapse_2_progression,
           relapse_3_progression, date_rip_last_f_up) %>%
    mutate(id = reorder(id, x1st_treatment)) %>%
    gather(type, date, -id, -outcome) %>%
    mutate(type = factor(type, levels = levs, labels = labs))
  

```


```{r}

  ggplot(times, aes(y = id, x = date, color = type)) +
    geom_point(size = 3, alpha = 0.8) +
    geom_line(color = "grey", line_type = "dashed") +
    scale_color_manual("", values = brewer.pal(9, "Set1")[c(1:5, 9)]) +
    theme(axis.text.y = element_blank(), 
          axis.ticks.y = element_blank(),
          strip.background = element_blank(),
          panel.grid = element_blank(), 
          panel.background = element_blank(), 
          legend.position = "bottom") +
    facet_wrap(~outcome, ncol = 1) +
    xlab("") +
    ylab("")

```


```{r}

  df <- select(data, starts_with("dx_to")) %>%
    gather(type, days) %>%
    group_by(type) %>%
    mutate(mean_time = mean(days)) %>%
    mutate(type = reorder(type, mean_time)) %>%
    ungroup() 

  ggplot(df, aes(x = days, fill = type, color = type)) +
    geom_density(color = "black", adjust = 2) +
    geom_rug(size = 1) +
    facet_wrap(~type, ncol = 1, scales = "free_y") +
    scale_fill_viridis("", discrete = TRUE, end = 0.8) +
    scale_color_viridis("", discrete = TRUE, end = 0.8)

```

```{r}

  map(select(data, starts_with("dx_to")), summary) %>% pander()

```


```{r}


  df <- select(data, starts_with("tx_to")) %>%
    gather(type, days) %>%
    group_by(type) %>%
    mutate(mean_time = mean(days)) %>%
    mutate(type = reorder(type, mean_time)) %>%
    ungroup() 

  ggplot(df, aes(x = days, fill = type, color = type)) +
    geom_density(color = "black", adjust = 2) +
    geom_rug(size = 1) +
    facet_wrap(~type, ncol = 1, scales = "free_y") +
    scale_fill_viridis("", discrete = TRUE, end = 0.8) +
    scale_color_viridis("", discrete = TRUE, end = 0.8)

```
```{r}

  map(select(data, starts_with("tx_to")), summary) %>% pander()

```


## Table 1

```{r table1_describe}

  descript <- select(data, age_dx, gender, p53_exp, bcl2_percent)

  data_frame(
    Variable = name.1(descript),
    Missing   = n.miss(descript),
    "Mean SD or n (%)" = summary.1(descript),
    "Median [IQR]" = med.iqr(descript),
    "(Min, Max)" = min.max(descript)
    ) %>% 
  flextable() 
  
```



# Time to event models

### Empty model

```{r basic_survfit}

  sf <- survfit(Surv(tx_to_eos, died) ~ 1, data = data) 

  pander(sf)

```

```{r}

  p1 <- ggsurvplot(
    sf, 
    data = data, 
    conf.int = TRUE, 
    surv.median.line = "hv", 
    risk.table = FALSE, 
    break.x.by = 26, 
    xlab = "Weeks"
    #xlim = c(0, lm)
    ) 

  p1$plot +  
    scale_color_discrete(guide = FALSE) 
  
```
### P53

```{r p53_survfit}

  sf <- survfit(Surv(tx_to_eos, died) ~ p53_exp, data = data) 

  pander(sf)

```

```{r}

  p1 <- ggsurvplot(
    sf, 
    data = data, 
    conf.int = TRUE, 
    risk.table = TRUE, 
    break.x.by = 26, 
    xlab = "Weeks"
    #xlim = c(0, lm)
    ) 

  p1 
  
```

### P53

```{r bcl2_survfit}

  sf <- survfit(Surv(tx_to_eos, died) ~ bcl2_percent, data = data) 

  pander(sf)

```

```{r}

  p1 <- ggsurvplot(
    sf, 
    data = data, 
    conf.int = TRUE, 
    risk.table = TRUE, 
    break.x.by = 26, 
    xlab = "Weeks"
    #xlim = c(0, lm)
    ) 

  p1 
  
```

### Both

```{r both_markers_survfit}

  sf <- survfit(Surv(tx_to_eos, died) ~ bcl2_percent + p53_exp, data = data) 

  pander(sf)

```

```{r}

  p1 <- ggsurvplot(
    sf, 
    data = data, 
    conf.int = TRUE, 
    risk.table = TRUE, 
    break.x.by = 26, 
    xlab = "Weeks"
    #xlim = c(0, lm)
    ) 

  p1 
  
```


Cox models


```{r}

  os <- with(data, Surv(tx_to_eos, died))

# ddist <- datadist(data) # For RMS
# options(datadist = "ddist")

  cox1 <- coxph(os ~  bcl2_percent,                             data = data)
  cox2 <- coxph(os ~                 p53_exp,                   data = data)
  cox3 <- coxph(os ~  bcl2_percent + p53_exp,                   data = data)
  cox4 <- coxph(os ~  bcl2_percent + p53_exp + gender + age_dx, data = data)

  tab_model(cox1, cox2, cox3, cox4, dv.labels = rep("OS", 3))

```


```{r code_book}

#  print(summarytools::dfSummary(data), method = "render")

```

```{r sysinfo}

  DescTools::SysInfo()

```



